package com.example.mandateguard.enums;

public enum AuditEventType {
    PRINCIPAL_REGISTERED,
    AGENT_REGISTERED,
    AGENT_ACTIVATED,
    AGENT_SUSPENDED,
    MANDATE_CREATED,
    MANDATE_ACTIVATED,
    MANDATE_SUSPENDED,
    MANDATE_REVOKED,
    PAYMENT_REQUEST_RECEIVED,
    SIGNATURE_VERIFIED,
    SIGNATURE_REJECTED,
    PAYMENT_ALLOWED,
    PAYMENT_DENIED,
    APPROVAL_REQUESTED,
    PAYMENT_APPROVED,
    PAYMENT_REJECTED,
    PAYMENT_EXECUTED,
    PAYMENT_FAILED,
    RISK_HOLD_CREATED
}