package com.example.mandateguard.enums;

public enum DecisionReasonCode {
    ALL_RULES_PASSED,
    MANDATE_NOT_ACTIVE,
    MANDATE_EXPIRED,
    MANDATE_REVOKED,
    MANDATE_EXHAUSTED,
    AGENT_NOT_AUTHORIZED,
    CURRENCY_NOT_ALLOWED,
    COUNTRY_NOT_ALLOWED,
    MERCHANT_NOT_ALLOWED,
    MERCHANT_CATEGORY_NOT_ALLOWED,
    SINGLE_AMOUNT_LIMIT_EXCEEDED,
    TOTAL_BUDGET_EXCEEDED,
    TRANSACTION_LIMIT_EXCEEDED,
    HUMAN_APPROVAL_REQUIRED,
    PRINCIPAL_REJECTED,
    RISK_HOLD,
    IDEMPOTENCY_CONFLICT
}